version: '2.4'
services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db_blog_pessoal
    networks:
      - generation-network
      
  blogpessoal-api:
    restart: always
    build: ./blogpessoal-api/rede-social-security
    working_dir: /blogpessoal-api/rede-social-security
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./blogpessoal-api:/blogpessoal-api
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - generation-network

  blogpessoal-front:
    image: nginx
    volumes:
      - ./blogpessoal-front/dist/blogpessoal:/usr/share/nginx/html/
    ports:
      - "4200:8080"
    networks:
      - generation-network

networks:
  generation-network:
    driver: bridge